name: CordCloud

on:
  schedule:
    - cron: "30 16 * * *"
    - cron: "00 04 * * *"
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    steps:
      - uses: JiahongCHENn/cordcloud-action@main
        with:
          email: ${{ secrets.CC_EMAIL }}
          passwd: ${{ secrets.CC_PASSWD }}
